name = "shortlink-v2"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
BASE_URL = "https://shortlink-v2.cwwx1818.workers.dev"

# KV namespace for storing URL mappings
[[kv_namespaces]]
binding = "URL_STORAGE"
id = "cacb14ce3a64488caf4a9fbb498e7b4e"
preview_id = "cacb14ce3a64488caf4a9fbb498e7b4e"