name = "shortlink"
main = "src/worker.js"
compatibility_date = "2023-10-01"

[vars]
BASE_URL = "https://shortlink.cwwx1818.workers.dev"

# KV namespace for storing URL mappings
[[kv_namespaces]]
binding = "URL_STORAGE"
id = "94f74c3d355a4dc6a61e57878ccc989c"
preview_id = "94f74c3d355a4dc6a61e57878ccc989c"

# Optional: Custom domain
# [env.production]
# routes = [
#   { pattern = "short.example.com/*", zone_name = "example.com" }
# ]