name = "shortlink"
main = "src/worker.js"
compatibility_date = "2023-10-01"

[vars]
BASE_URL = "https://shortlink.cwwx1818.workers.dev"

# KV namespace for storing URL mappings
# 暂时注释掉，先部署看界面效果，然后再创建正确的KV命名空间
# [[kv_namespaces]]
# binding = "URL_STORAGE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Optional: Custom domain
# [env.production]
# routes = [
#   { pattern = "short.example.com/*", zone_name = "example.com" }
# ]