name = "shortlink-fresh-2024"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Temporarily comment out KV to test basic deployment
# [[kv_namespaces]]
# binding = "URL_STORAGE"
# id = "cacb14ce3a64488caf4a9fbb498e7b4e"
# preview_id = "cacb14ce3a64488caf4a9fbb498e7b4e"